spring:
    application:
      name: SpringSecurityExample
    datasource:
        url: jdbc:postgresql://localhost:5432/realtrackerdb
        username: postgres
        password: 2471
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    jwt:
        secret:
            key: ${JWT_SECRET_KEY}
