spring:
    task:
        scheduling:
            enabled: true
    application:
        name: SpringSecurityExample
    datasource:
        url: jdbc:postgresql://localhost:5432/realtrackerdb
        username: postgres
        password: 2471
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true