spring:
    application:
      name: SpringSecurityExample
    security:
      user:
          username: hitta
          password: 321
    datasource:
        url: jdbc:postgresql://localhost:5432/realtrackerdb
        username: postgres
        password: 2471
